

SOURCE=sin2012_abstract_xkimer00_xhelle03.tex

all:
	pdflatex $(SOURCE)

clean:
	rm -f *.dvi *.log $(SOURCE).blg $(SOURCE).bbl $(SOURCE).toc *.aux $(SOURCE).out $(SOURCE).lof $(SOURCE).nav $(SOURCE).snm
	rm -f $(SOURCE).pdf

